version: '3.8'

services:
  platlas:
    build: ./app
    image: platlas:latest
    expose:
      - 3838
    networks:
      - sp-net
  shinyproxy:
    build: ./shinyproxy
    expose:
      - 8080
    depends_on: 
      - platlas
    networks:
      - sp-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/opt/shinyproxy/container-logs/
  nginx: 
    image: nginx:1.25.1
    restart: unless-stopped
    ports:
      - 3848:80
    networks:
      - sp-net
    depends_on:
      - shinyproxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
  sp-net: 
